### ISSUE TITLE
Uncaught TypeError: Cannot read property 'undefined' of undefined

### ISSUE THREAD

**Issue by RonyNasr** [chrisgriffith/autocomplete-angular-material#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [autocomplete-angular-material](https://github.com/chrisgriffith/autocomplete-angular-material) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'undefined' of undefined

```
At /home/rony/.atom/packages/autocomplete-angular-material/lib/provider.coffee:176

TypeError: Cannot read property 'undefined' of undefined
    at Object.getTagAttributes (/packages/autocomplete-angular-material/lib/provider.coffee:176:5)
    at Object.getAttributeNameCompletions (/packages/autocomplete-angular-material/lib/provider.coffee:103:22)
    at Object.getSuggestions (/packages/autocomplete-angular-material/lib/provider.coffee:20:8)
    at /opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.3 
autocomplete-angular-material 0.4.0 
color-picker 2.2.5 
language-vue 0.23.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.3 
pretty-json 1.6.3 
seti-syntax 1.1.3 
seti-ui 1.9.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by chrisgriffith** [comment]
I am guessing there may be a conflict with vue2 autocomplete package. I do know that autocomplete engine that I used only allows one autocomplete to be installed.
